// src/routes/login/+page.svelte
<script lang="ts">
	import { z } from 'zod';

	import { goto } from '$app/navigation';
	import { resolve } from '$app/paths';
	import { page } from '$app/state';
	import { authClient } from '$lib/auth-client';
	import AuthShell from '$lib/ui/AuthShell.svelte';
	import Icon from '$lib/ui/Icon.svelte';

	const schema = z.object({
		email: z.string().email('Email invalide'),
		password: z.string().min(1, 'Mot de passe requis')
	});

	let email = $state('');
	let password = $state('');
	let remember = $state(true);
	let error = $state('');
	let loading = $state(false);

	async function submit(e: SubmitEvent) {
		e.preventDefault();
		error = '';
		const parsed = schema.safeParse({ email, password });
		if (!parsed.success) {
			error = parsed.error.issues[0]?.message ?? 'Données invalides';
			return;
		}
		loading = true;
		const { error: err } = await authClient.signIn.email({
			email: parsed.data.email,
			password: parsed.data.password
		});
		loading = false;
		if (err) {
			error = err.message ?? 'Identifiants invalides';
			return;
		}
		const next = page.url.searchParams.get('next') ?? '/';
		await goto(resolve(next as '/'), { invalidateAll: true });
	}
</script>

<AuthShell>
	<h1 class="login-h1">Bon retour</h1>
	<p class="login-sub">Connecte-toi pour suivre tes dépenses selon la méthode 50/30/20.</p>

	<form onsubmit={submit}>
		<label class="field">
			<span>Email</span>
			<input
				bind:value={email}
				type="email"
				placeholder="toi@example.com"
				autocomplete="email"
				required
			/>
		</label>

		<label class="field">
			<span>Mot de passe</span>
			<input
				bind:value={password}
				type="password"
				placeholder="••••••••"
				autocomplete="current-password"
				required
			/>
		</label>

		<div class="login-remember">
			<button
				type="button"
				class="login-check"
				class:on={remember}
				aria-label="Rester connecté"
				aria-pressed={remember}
				onclick={() => (remember = !remember)}
			>
				{#if remember}<Icon name="x" size={10} />{/if}
			</button>
			<span>Rester connecté sur cet appareil</span>
		</div>

		{#if error}
			<p
				role="alert"
				style="margin: 0 0 12px; padding: 8px 10px; border-radius: 6px; background: oklch(0.95 0.04 25); color: oklch(0.40 0.18 25); font-size: 13px;"
			>
				{error}
			</p>
		{/if}

		<button
			type="submit"
			class="btn btn-primary"
			disabled={loading}
			style="width: 100%; justify-content: center; padding: 12px; font-size: 14px; margin-top: 6px;"
		>
			{loading ? 'Connexion…' : 'Se connecter'}
		</button>
	</form>

	<p class="login-switch">
		Pas encore de compte ? <a class="login-link" href={resolve('/register')}>Créer un compte</a>
	</p>
</AuthShell>

// Maquette/login.jsx
// Login page

function Login({ onLogin }) {
  const [email, setEmail] = useState('camille@example.com');
  const [password, setPassword] = useState('••••••••');
  const [mode, setMode] = useState('signin'); // 'signin' | 'signup'
  const [remember, setRemember] = useState(true);

  const submit = (e) => {
    e.preventDefault();
    onLogin();
  };

  return (
    <div className="login-page">
      <div className="login-left">
        <div className="login-brand">
          <div className="brand-mark">B</div>
          <span className="brand-name">Budget</span>
        </div>

        <div className="login-card">
          <h1 className="login-h1">{mode === 'signin' ? 'Bon retour' : 'Créer un compte'}</h1>
          <p className="login-sub">
            {mode === 'signin'
              ? 'Connecte-toi pour suivre tes dépenses selon la méthode 50/30/20.'
              : 'Quelques secondes pour démarrer.'}
          </p>

          <form onSubmit={submit}>
            <div className="field">
              <label>Email</label>
              <input
                type="email"
                placeholder="toi@example.com"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                autoFocus
              />
            </div>

            <div className="field">
              <label>
                Mot de passe
                {mode === 'signin' && (
                  <button type="button" className="login-link" style={{ float: 'right', textTransform: 'none', letterSpacing: 0, fontWeight: 500 }}>
                    Mot de passe oublié ?
                  </button>
                )}
              </label>
              <input
                type="password"
                placeholder="••••••••"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
              />
            </div>

            {mode === 'signin' && (
              <label className="login-remember">
                <span className={`login-check ${remember ? 'on' : ''}`} onClick={(e) => { e.preventDefault(); setRemember(v => !v); }}>
                  {remember && <Icon name="x" size={10} />}
                </span>
                <span>Rester connecté sur cet appareil</span>
              </label>
            )}

            <button type="submit" className="btn btn-primary" style={{ width: '100%', justifyContent: 'center', padding: '12px', fontSize: 14, marginTop: 6 }}>
              {mode === 'signin' ? 'Se connecter' : 'Créer le compte'}
            </button>
          </form>

          <div className="login-divider"><span>ou</span></div>

          <button className="btn btn-ghost login-sso" onClick={onLogin}>
            <span style={{ fontWeight: 600, fontFamily: 'serif' }}>G</span> Continuer avec Google
          </button>
          <button className="btn btn-ghost login-sso" onClick={onLogin}>
            <span></span> Continuer avec Apple
          </button>

          <p className="login-switch">
            {mode === 'signin' ? "Pas encore de compte ?" : "Déjà inscrit ?"}{' '}
            <button type="button" className="login-link" onClick={() => setMode(mode === 'signin' ? 'signup' : 'signin')}>
              {mode === 'signin' ? "Créer un compte" : "Se connecter"}
            </button>
          </p>
        </div>

        <div className="login-foot">
          © 2026 Budget · <button className="login-link">Confidentialité</button> · <button className="login-link">Conditions</button>
        </div>
      </div>

      <div className="login-right">
        <div className="login-hero">
          <div className="login-hero-tag">Méthode 50 / 30 / 20</div>
          <div className="login-hero-title">
            Trois enveloppes.<br />
            Une vie financière<br />
            sereine.
          </div>

          <div className="login-hero-cards">
            <div className="login-hero-card env-necessities">
              <div className="login-hero-card-pct">50<span>%</span></div>
              <div className="login-hero-card-label">Nécessités</div>
              <div className="login-hero-card-bar"><span style={{ width: '64%' }}></span></div>
              <div className="login-hero-card-meta">€1 162 / €1 600</div>
            </div>
            <div className="login-hero-card env-wants">
              <div className="login-hero-card-pct">30<span>%</span></div>
              <div className="login-hero-card-label">Envies</div>
              <div className="login-hero-card-bar"><span style={{ width: '23%' }}></span></div>
              <div className="login-hero-card-meta">€220 / €960</div>
            </div>
            <div className="login-hero-card env-investments">
              <div className="login-hero-card-pct">20<span>%</span></div>
              <div className="login-hero-card-label">Investissements</div>
              <div className="login-hero-card-bar"><span style={{ width: '100%' }}></span></div>
              <div className="login-hero-card-meta">€650 / €640</div>
            </div>
          </div>

          <div className="login-hero-quote">
            « Mon loyer, mes courses, mon livret A — tout est rangé tout seul. »
            <div className="login-hero-quote-author">Camille, utilisatrice depuis 8 mois</div>
          </div>
        </div>
      </div>
    </div>
  );
}

window.Login = Login;
